In [1]:
import csv                       #use library csv to open and read csv data
import numpy as np 
import math
import datetime
np.set_printoptions(threshold=np.inf)

path='/home/mz/Desktop/breast-cancer-wisconsin.data'

with open(path,'r') as cancerdata:
    reader = csv.reader(cancerdata) 
    rows= [row for row in reader]
    
cdata=np.array(rows)               #change rows' datatype into array

todelete=np.where(cdata=='?')               #save row number of 16 arrays which need to be deleted
#print(todelete[0])
ddataset=np.delete(cdata, todelete[0], axis = 0) #delete those rows which contain ‘？’

#print("The type and shape of cdata is",type(cdata), cdata.shape)
#print("The type and shape of ddataset is",type(ddataset), ddataset.shape)
test=np.where(ddataset=='?')                #Check if there are still '?' in ndarray ddataset
#print("The new dataset is contains ? in ", test)
#print(ddataset)
print('\n')
cdataset = ddataset.astype(np.float) #change datatype from string to float
#print(cdataset)

dataset = np.delete(cdataset,0,axis = 1) #处理好的数据
for i in range(dataset.shape[0]):
    if dataset[i,dataset.shape[1]-1]==2: dataset[i,dataset.shape[1]-1]=0
    else: dataset[i,dataset.shape[1]-1]=1
#print(dataset,dataset.shape)
#data0=dataset
datash = dataset
np.random.shuffle(datash)
data0=datash


#k fold validation
k=5
n0 = data0.shape[0]
X_test = data0[0:int(n0/k), 0:-1 ]
y_test = data0[0:int(n0/k), -1 ]

data2 = np.delete(data0, range(0,int(n0/k)),axis = 0)#delete testset from data
X_all = data2[:,0:-1]
y_all = data2[:,-1]


n1 = data2.shape[0]#number of rows in data2 for training and verti
X_valid = [[]for i in range(k)]
X_train = [[]for i in range(k)]
y_valid = [[]for i in range(k)]
y_train = [[]for i in range(k)]
trainset = [[]for i in range(k)]
for i in range(0,k):#generate k training sets and validation sets
    X_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), 0:-1])
    y_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), -1])
    a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
    trainset[i] = np.delete(data2, a , axis=0)
    X_train[i] = trainset[i][:,0:-1]
    y_train[i] = trainset[i][:,-1]
    print('valid i=', i, X_train[i].shape)
    print('valid i=', i, y_train[i].shape)



valid i= 0 (438, 9)
valid i= 0 (438,)
valid i= 1 (438, 9)
valid i= 1 (438,)
valid i= 2 (437, 9)
valid i= 2 (437,)
valid i= 3 (438, 9)
valid i= 3 (438,)
valid i= 4 (437, 9)
valid i= 4 (437,)


In [23]:
#1st
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(136,)
The accuracy is 0.9485294117647058
[[40  3]
 [ 4 89]]
used time is 0:00:00.059431


In [27]:
#2nd
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(136,)
The accuracy is 0.9632352941176471
[[46  3]
 [ 2 85]]
used time is 0:00:00.046075


In [33]:
#3rd
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(136,)
The accuracy is 0.9558823529411765
[[38  2]
 [ 4 92]]
used time is 0:00:00.061332


In [35]:
#4th
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(136,)
The accuracy is 0.9779411764705882
[[44  2]
 [ 1 89]]
used time is 0:00:00.059389


In [37]:
#5th
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(136,)
The accuracy is 0.9926470588235294
[[49  1]
 [ 0 86]]
used time is 0:00:00.077264


In [5]:
def Py(label,inClass):#input is label and value of label; This function returns the probability of value: label
    tr=label
    N=0
    for i in range(tr.shape[0]):
        if tr[i]==inClass: N=N+1
    
    Py=N/tr.shape[0]
    return Py

def N(label,inClass):#input is trainingset; This function returns the number of value: label in vertor label
    tr=label
    N=0
    for i in range(tr.shape[0]):
        if tr[i]==inClass: N=N+1
    return N

def rema(data,label,clas):#Divide a matrix into two matrices according to different value of label
    #tr = np.c_[data,label]
    #n = tr.shape
    #last = data
    #print(last)
    tr = data
    a = np.where(label==clas)
    
    #print(a[0])
    
    Subdata = tr[a[0],:]
    
    #Subdata = np.zeros([b,n[1]])
    #Subdata = np.delete(tr, a[0], axis=0)
    '''
    for i in range(tr.shape[0]):
        if tr[i,tr.shape[1]-1]==clas:
            Subdata[i,] = tr[i,]
    '''
    #print(Subdata)
    #print(Subdata2)
    return Subdata 

def mean(data,label,inClass):#calculate the mean of a matrix
    M=rema(data,label,inClass)
    #Num=N(label,inClass)
    Num=M.shape[0]
    u=np.zeros(M.shape[1])
    for i in range(M.shape[1]):
        u[i]= 1/Num * sum(M[:,i])
        #print(u)
    return u

def coVar(data,label):#calculate the co-variance matrix with help of function cov from numpy
    tr = data
    M0 = rema(tr,label,0)
    M1 = rema(tr,label,1)
    #u0 = mean(tr,Cl0)
    #u1 = mean(tr,Cl1)

    pre0 = M0[: , 0:M0.shape[1]]
    pre0 = pre0.T
    cov0 = np.cov(pre0)
    #print(cov0)

    pre1 = M1[:,0:M1.shape[1]]
    pre1 = pre1.T
    cov1 = np.cov(pre1)
    #print(cov1)
    cov = (cov0 + cov1)/(tr.shape[0]-2)
    #print(cov)
    return cov

#data:traindat label:train label testdata:testdata
def pred(data,label,testdata): #Training and finding covariance matirx in order to produce the prediction function and test produced cov matrix with testdata
    tr = data
    tt = label
    
    u1t = mean(tr,tt,1)
    u1=u1t.reshape(u1t.shape[0],1)
    
    u0t = mean(tr,tt,0)
    u0 = u0t.reshape(u0t.shape[0],1)
    
    cov = coVar(tr,tt)
    inv = np.linalg.inv(cov)
    
    result = np.zeros(testdata.shape[0])
    
    for i in range(testdata.shape[0]):
        logodd = math.log(Py(tt,0)/(1-Py(tt,0))) - 0.5*np.dot(np.dot(u1t,inv),u1) + 0.5*np.dot(np.dot(u0t,inv),u0) + np.dot(np.dot(testdata[i,],inv),u1-u0)             
        if logodd>0:result[i]=1
        else:result[i]=0
    return result

#return the accuracy through comparing label and produced result
def Accu(result,label):
    rV = label
    n = 0
    N = result.shape[0]
    for i in range(result.shape[0]):
        if rV[i] == result[i]:n=n+1
    
    print('The accuracy is',n/N)
    return n/N

def fit(X_train, y_train, X_test):
    result = pred(X_all,y_all,X_test)
    print(result.shape)
    return result

#return the confusion matrix
def conmat(result,y):
    rv = y
    #print(result.shape)
    #print(rv.shape)
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(result.shape[0]):
        if ((result[i]==1)&(rv[i]==1)): TP = TP+1
        if ((result[i]==0)&(rv[i]==0)): TN = TN+1
        if ((result[i]==0)&(rv[i]==1)): FN = FN+1
        if ((result[i]==1)&(rv[i]==0)): FP = FP+1
    metrix = np.array([[TP,FP], [FN,TN]])
    return metrix

In [6]:
ergeb = fit(X_all,y_all,X_test)
conmat(ergeb,y_test)
Accu(ergeb,y_test)

(136,)
The accuracy is 0.9485294117647058


0.9485294117647058

In [25]:
ergeb = fit(X_all,y_all,X_test)
conmat(ergeb,y_test)
Accu(ergeb,y_test)

(136,)
The accuracy is 0.9485294117647058


0.9485294117647058