In [1]:
import csv                       #use library csv to open and read csv data
import numpy as np 
import math
import datetime

path='/home/mz/Desktop/winequality-red.csv'

with open(path,'r') as winedata:
    reader = csv.reader(winedata, delimiter=';') #maybe csv from mac? Set the delimiter to ';'
    rows= [row for row in reader]
    
#print (rows[0])
data=np.array(rows)               #change rows' datatype into array
wdata=np.delete(data,0,axis = 0) #delete the name row

#dataset will be used for K-fold validation
wdataset = wdata.astype(np.float)

for n in range(0,wdataset.shape[0]):                #classify the quality. Positiv:1  Negativ:2
    if wdataset[n,11]>5: wdataset[n,11]=1
    else: wdataset [n,11]=0
        

datash = wdataset
np.random.shuffle(datash)
data0=datash

k=5
n0 = data0.shape[0]
X_test = data0[0:int(n0/k), 0:-1 ]
y_test = data0[0:int(n0/k), -1 ]
print(y_test)
print(data0[:,data0.shape[1]-2])

data2 = np.delete(data0, range(0,int(n0/k)),axis = 0)#delete testset from data
X_all = data2[:,0:-1]
y_all = data2[:,-1]


n1 = data2.shape[0]#number of rows in data2 for training and verti
X_valid = [[]for i in range(k)]
X_train = [[]for i in range(k)]
y_valid = [[]for i in range(k)]
y_train = [[]for i in range(k)]
trainset = [[]for i in range(k)]
for i in range(0,k):
    X_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), 0:-1])
    y_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), -1])
    a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
    trainset[i] = np.delete(data2, a , axis=0)
    X_train[i] = trainset[i][:,0:-1]
    y_train[i] = trainset[i][:,-1]
    print('valid i=', i, X_train[i].shape)
    print('valid i=', i, y_train[i].shape)

[1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0.
 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1.
 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0.
 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1.
 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 1.]
[10.03333333 10.         11.

In [39]:
#5th
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(319,)
The accuracy is 0.774294670846395
[[124  34]
 [ 38 123]]
used time is 0:00:00.251820


In [37]:
#4th
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(319,)
The accuracy is 0.7460815047021944
[[119  25]
 [ 56 119]]
used time is 0:00:00.229904


In [35]:
#3rd
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(319,)
The accuracy is 0.7492163009404389
[[122  38]
 [ 42 117]]
used time is 0:00:00.253711


In [33]:
#2nd
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(319,)
The accuracy is 0.7586206896551724
[[125  35]
 [ 42 117]]
used time is 0:00:00.219391


In [31]:
#1st
start = datetime.datetime.now()
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)
at=conmat(ergeb,y_test)
print(at)
end = datetime.datetime.now()
print ('used time is',end-start)

(319,)
The accuracy is 0.7178683385579937
[[129  28]
 [ 62 100]]
used time is 0:00:00.227294


In [2]:
def Py(label,inClass):#input is trainingset/data2; This function returns the probability of value: label
    tr=label
    N=0
    for i in range(tr.shape[0]):
        if tr[i]==inClass: N=N+1
    
    Py=N/tr.shape[0]
    return Py

def N(label,inClass):#input is trainingset/data2; This function returns the number of value: label
    tr=label
    N=0
    for i in range(tr.shape[0]):
        if tr[i]==inClass: N=N+1
    return N

def rema(data,label,clas):#Divide a matrix into two matrices according to different value of label
    #tr = np.c_[data,label]
    #n = tr.shape
    #last = data
    #print(last)
    tr = data
    a = np.where(label==clas)
    
    #print(a[0])
    
    Subdata = tr[a[0],:]
    
    #Subdata = np.zeros([b,n[1]])
    #Subdata = np.delete(tr, a[0], axis=0)
    '''
    for i in range(tr.shape[0]):
        if tr[i,tr.shape[1]-1]==clas:
            Subdata[i,] = tr[i,]
    '''
    #print(Subdata)
    #print(Subdata2)
    return Subdata 

def mean(data,label,inClass):#calculate the mean of a matrix
    M=rema(data,label,inClass)
    #Num=N(label,inClass)
    Num=M.shape[0]
    u=np.zeros(M.shape[1])
    for i in range(M.shape[1]):
        u[i]= 1/Num * sum(M[:,i])
        #print(u)
    return u

def coVar(data,label):#calculate the co-variance matrix with help of function cov from numpy
    tr = data
    M0 = rema(tr,label,0)
    M1 = rema(tr,label,1)
    #u0 = mean(tr,Cl0)
    #u1 = mean(tr,Cl1)

    pre0 = M0[: , 0:M0.shape[1]]
    pre0 = pre0.T
    cov0 = np.cov(pre0)
    #print(cov0)

    pre1 = M1[:,0:M1.shape[1]]
    pre1 = pre1.T
    cov1 = np.cov(pre1)
    #print(cov1)
    cov = (cov0 + cov1)/(tr.shape[0]-2)
    #print(cov)
    return cov

#data:traindat label:train label testdata:testdata
def pred(data,label,testdata): #Training and finding covariance matirx in order to produce the prediction function and test produced cov matrix with testdata
    tr = data
    tt = label
    
    u1t = mean(tr,tt,1)
    u1=u1t.reshape(u1t.shape[0],1)
    
    u0t = mean(tr,tt,0)
    u0 = u0t.reshape(u0t.shape[0],1)
    
    cov = coVar(tr,tt)
    inv = np.linalg.inv(cov)
    
    result = np.zeros(testdata.shape[0])
    
    for i in range(testdata.shape[0]):
        logodd = math.log(Py(tt,0)/(1-Py(tt,0))) - 0.5*np.dot(np.dot(u1t,inv),u1) + 0.5*np.dot(np.dot(u0t,inv),u0) + np.dot(np.dot(testdata[i,],inv),u1-u0)             
        if logodd>0:result[i]=1
        else:result[i]=0
    return result

#return the accuracy through comparing label and produced result
def Accu(result,label):
    rV = label
    n = 0
    N = result.shape[0]
    for i in range(result.shape[0]):
        if rV[i] == result[i]:n=n+1
    
    print('The accuracy is',n/N)
    return n/N

def fit(X_train, y_train, X_test):
    result = pred(X_all,y_all,X_test)
    print(result.shape)
    return result

#return the confusion matrix
def conmat(result,y):
    rv = y
    #print(result.shape)
    #print(rv.shape)
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(result.shape[0]):
        if ((result[i]==1)&(rv[i]==1)): TP = TP+1
        if ((result[i]==0)&(rv[i]==0)): TN = TN+1
        if ((result[i]==0)&(rv[i]==1)): FN = FN+1
        if ((result[i]==1)&(rv[i]==0)): FP = FP+1
    metrix = np.array([[TP,FP], [FN,TN]])
    return metrix

In [3]:
ergeb = fit(X_all,y_all,X_test)
Accu(ergeb,y_test)

(319,)
The accuracy is 0.7210031347962382


0.7210031347962382