In [5]:
import csv                       #use library csv to open and read csv data
import numpy as np 
import math
import datetime
import random
path='/home/mz/Desktop/winequality-red.csv'

with open('winequality-red.csv', 'r')  as winedata:
    reader = csv.reader(winedata, delimiter=';') #maybe csv from mac? Set the delimiter to ';'
    rows= [row for row in reader]
    
#print (rows[0])
data=np.array(rows)               #change rows' datatype into array
dataset=np.delete(data,0,axis = 0) #delete the name row

#wdataset will be used for K-fold validation
wdataset = dataset.astype(np.float)
for n in range(0,wdataset.shape[0]): 
    #classify the quality. Positiv:1  Negativ:2
    if wdataset[n,11]>5: wdataset[n,11]=1
    else: wdataset [n,11]=0
wdataset[:,0:-1]=wdataset[:,0:-1]-np.mean(wdataset[:,0:-1],axis=0)
#wdataset[:,:]=wdataset[:,:]-np.mean(wdataset[:,:],axis=0)
#for i in range(wdataset.shape[0]):
#    for j in range(wdataset.shape[1]-1):
#        wdataset[i,j]=wdataset[i,j]*wdataset[i,j]
wdataset[:,0]=wdataset[:,0]/0.015388812
wdataset[:,1]=wdataset[:,1]/0.15253538
wdataset[:,2]=wdataset[:,2]/0.051244515
wdataset[:,3]=wdataset[:,3]/0.000188558

wdataset[:,4]=wdataset[:,4]/0.016616901

wdataset[:,5]=wdataset[:,5]/0.002566036

wdataset[:,6]=wdataset[:,6]/0.034262117

wdataset[:,7]=wdataset[:,7]/0.030596736

wdataset[:,8]=wdataset[:,8]/0.003332914

wdataset[:,9]=wdataset[:,9]/0.063200491
wdataset[:,10]=wdataset[:,10]/0.226734368

print(wdataset)

datash = wdataset
np.random.shuffle(datash)
data0=datash



asd=[1,2,9,10]
k=5
n0 = data0.shape[0]
X_test = data0[0:int(n0/k), asd ]
y_test = data0[0:int(n0/k), -1 ]
data2 = np.delete(data0, range(0,int(n0/k)),axis = 0)#delete testset from data
n1 = data2.shape[0]#number of rows in data2 for training and validation
X_all = data2[:,asd]
y_all = data2[:,-1]
X_valid = [[]for i in range(k)]
X_train = [[]for i in range(k)]
y_valid = [[]for i in range(k)]
y_train = [[]for i in range(k)]
trainset = [[]for i in range(k)]

for i in range(0,k):
    X_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), asd])
    y_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), -1])
    a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
    trainset[i] = np.delete(data2, a , axis=0)
    X_train[i] = trainset[i][:,asd]
    y_train[i] = trainset[i][:,-1]
    print('valid i=', i, X_train[i].shape)
    print('valid i=', i, y_train[i].shape)

[[-5.97601214e+01  1.12878394e+00 -5.28789490e+00 ... -1.55297596e+00
  -4.51181320e+00  0.00000000e+00]
 [-3.37672117e+01  2.30883804e+00 -5.28789490e+00 ...  3.45743469e-01
  -2.74763425e+00  0.00000000e+00]
 [-3.37672117e+01  1.52213531e+00 -4.50732356e+00 ... -1.28936388e-01
  -2.74763425e+00  0.00000000e+00]
 ...
 [-1.31240623e+02 -1.16828718e-01 -2.75103803e+00 ...  1.45332980e+00
   2.54490261e+00  1.00000000e+00]
 [-1.57233533e+02  7.68211855e-01 -2.94618087e+00 ...  8.20423325e-01
  -9.83455294e-01  0.00000000e+00]
 [-1.50735305e+02 -1.42799994e+00  3.88381840e+00 ...  2.92902309e-02
   2.54490261e+00  1.00000000e+00]]
valid i= 0 (1024, 4)
valid i= 0 (1024,)
valid i= 1 (1024, 4)
valid i= 1 (1024,)
valid i= 2 (1024, 4)
valid i= 2 (1024,)
valid i= 3 (1024, 4)
valid i= 3 (1024,)
valid i= 4 (1024, 4)
valid i= 4 (1024,)


In [6]:
print(X_train[1])

[[-1.23132425  4.07896124  0.50397009  7.39639473]
 [ 0.0142884  -0.60446683 -1.8694292  -4.5118132 ]
 [ 0.27652265 -5.2878949  -1.55297596  3.42699209]
 ...
 [ 0.66987401 -4.89760923  1.4533298  -2.74763425]
 [ 0.70265329 -3.33646654  1.4533298   2.10385787]
 [-1.03464857  0.95667586  2.24446289  3.42699209]]


In [7]:
print(X_test)

[[ 2.04660379  1.34696153 -2.81878891 -5.83494741]
 [ 3.35777501 -4.31218072 -1.71120258 -2.30658951]
 [-1.10020713 -1.18989534 -2.02765581 -1.42450003]
 ...
 [ 0.83377042 -0.21418116 -3.76814862 -3.62972372]
 [ 2.04660379 -5.2878949  -1.71120258 -3.18867899]
 [ 0.99766682 -3.53160938 -2.18588243  2.98594735]]


In [8]:
print(X_all)

[[-1.23132425  4.07896124  0.50397009  7.39639473]
 [ 0.0142884  -0.60446683 -1.8694292  -4.5118132 ]
 [ 0.27652265 -5.2878949  -1.55297596  3.42699209]
 ...
 [ 0.66987401 -4.89760923  1.4533298  -2.74763425]
 [ 0.70265329 -3.33646654  1.4533298   2.10385787]
 [-1.03464857  0.95667586  2.24446289  3.42699209]]


In [29]:
def sigmoid(gamma):
    if gamma < 0:
        return 1 - 1/(1 + math.exp(gamma))
    else:
        return 1/(1 + math.exp(-gamma))
    

'''
def add(data,w):
            m = data.shape[1]
            summe = np.zeros(m-1)
            for i in range(0,data.shape[0]):
                a = data[i,0:(data.shape[1]-1)]*((data[i,(data.shape[1]-1)])-sigma(w, data[i,0:(data.shape[1]-1)]))
                summe = summe + a         
            return summe    
    
def gd(w,lr,data):
            neww = w + lr*add(data,w)
            return neww
'''

def findw(lr,n,data,y_train):
    traindata = data
    m = traindata.shape[1]#data的列数
    #w = [0,0,0,0,0,0,0,0,0,0,0]#除去最后一列的quality
    #w = [1,1,1,1,1,1,1,1,1,1,1]
    w = np.ones(m)
    #right = [0,0,0,0,0,0,0,0,0,0,0]
    #vector
    right = np.zeros(m)
    for i in range(1,n):#n次iteration
        #wt = np.array([w]).T#transport from row to column
        for j in range(0,traindata.shape[0]):
            right = right + traindata[j,]*(y_train[j]-sigmoid(np.dot(w,traindata[j,])))
            #print('right',j,right)
        #print('iteration = ',i,right)C=99999999999999999999999999999999999999999999999999999999999999
        for l in range(0,right.shape[0]):
            right[l]=right[l]*lr
        #print(right)
        w=w+right
        #print(w)
    return w



def predict(data,w):#already got w for prediction将预测结果写入第n+1列，即m=12.here using verti and test,仅将预测结果写入了第m+1行
        n = data.shape[0]
        result = np.zeros(n)
        for i in range(0,n):
            prob = sigmoid(np.dot(w,data[i,]))
            #prob = (1/math.sqrt(2*pi*sigma(w,data[i,0:n-1]))) * math.exp(-(1-np.transpose(w)*data[i,0:n-1]/2(sigma(w,data[i,0:n-1])*sigma(w,data[i,0:n-1]))))
            if prob>=0.5: result[i]=1
        return result
             
def accuracy(pred, y):#pred is result from fct predict
    real = y
    
    if pred.shape != real.shape:
        print('Error!!!')
        
    acc=0
    for i in range(pred.shape[0]):
        if pred[i]==real[i]:
            acc=acc+1
    Accuracy=acc/pred.shape[0]   
    #print('Accuracy is ',Accuracy)
    return Accuracy

def conmat(result,y):
    rv = y
    print(result.shape)
    print(rv.shape)
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(result.shape[0]):
        if ((result[i]==1)&(rv[i]==1)): TP = TP+1
        if ((result[i]==0)&(rv[i]==0)): TN = TN+1
        if ((result[i]==0)&(rv[i]==1)): FN = FN+1
        if ((result[i]==1)&(rv[i]==0)): FP = FP+1
    metrix = np.array([[TP,FP], [FN,TN]])
    return metrix
'''                    
def Accu(data):#the data is after prediction
        n = shape.data[0]
        m = shape.data[1]
        a = 0
        for i in range(0,n):
                if data[i,m-2]==data[i,m-1]: a=a+1
        Accuracy = a/n
        return Accuracy
  
    0
    
def kfold(k, data):
    n0 = data.shape[0]
    testset = data[0:int(n0/k), ]
    data2 = np.delete(data, range(0,int(n0/k)),axis = 0)#delete testset from data
    n1 = data2.shape[0]#number of rows in data2 for training and verti

    vertiset = [[]for i in range(k)]
    trainset = [[]for i in range(k)]
    
    for i in range(0,k):
        vertiset[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), :])
        print('verti i=', i, vertiset[i].shape)
        a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
        trainset[i] = np.delete(data2, a , axis=0)
'''      
    
def fit():#寻找w
    start = datetime.datetime.now()
    a_n = 7
    iter_n= 5
    numwewant = 40
    
    alpha = np.zeros(9*a_n)
    for i in range(9):
        alpha[i]= 1e-7*(i+1)
        alpha[i+9]= 1e-6*(i+1)
        alpha[i+18]= 1e-5*(i+1)
        alpha[i+27]= 1e-4*(i+1)
        alpha[i+36]= 1e-3*(i+1)
        alpha[i+45]= 1e-2*(i+1)
        alpha[i+54]= 1e-1*(i+1)
        #alpha[i+63]= (i+1)
        #alpha[i+72]= (i+1)*10
        #alpha[i+81]= (i+1)*100
    
    #n_iteration = [500, 1000, 1500]
    n_iteration = [500, 1000, 1500, 2500, 3000]
    
    pairs = [[]for i in range(a_n*iter_n*9)]
    n = 0
    
    #offer all possibilities for pairs of alpha and iteration
    for i in range(9*a_n):
        j = 0
        while j<5:
            pairs[n] = [alpha[i], n_iteration[j]]
            n = n+1
            j = j+1
             
    print(pairs)  
    
    print('\n')
    #print(pairs)
    
    #here we chose numwewant from 9*a_n*5
    para_pos = np.array(random.sample(range(0,a_n*iter_n*9), numwewant))#generate used pairs's position
    #result = np.zeros([80,256])
    result = [[]for i in range(numwewant)]#save the predict results
    print(para_pos)
    A = np.zeros(numwewant)#the avg accuracy vector for 80 pairs
    Accu = np.zeros([numwewant,5])#Accuracy for each validation
    #ln=0
    
    for i in range(numwewant):
        print('\n')
        pos = para_pos[i]
        print('pos',pos)
        para = pairs[pos]
        print('para',para)
        for j in range(5):
            #a = para[0]
            #b = para[1]
            #print(a)
            #print(b)
            lr = para[0]
            n = para[1]
            w_model = findw(lr,n,X_train[j],y_train[j])#find w according to X_train and y_train
            print('fold',j,'of model',i,'finished',w_model)
            result[i] = predict(X_valid[j],w_model)#using X_valid as input to produce prediction output
            #result = predict(X_valid[j],w_model)
            #result[ln] = predict(X_valid[j],w_model)
            #ln = ln+1
            Accu[i,j]= accuracy(result[i], y_valid[j])#compare result(output prediction) and real values y_valid
            print('Accuracy is',Accu[i,j])
            if j ==4: A[i] = np.sum(Accu[i,:])/5
            if j ==4: print('\033[1;35m Average accuracy is \033[0m',A[i])          
            print('\n')
            
            
  


        
    a = np.max(A)
    pos_max = np.where(A==a)
    location = pos_max[0][0]#location is a number which used to locate which random number in random vector
    print('used position',location)
    bestalpha = pairs[para_pos[location]][0]
    bestn = pairs[para_pos[location]][1]
    print('avg A is',A)
    print('max',np.max(A))
    print('max_pos',pos_max)
    print('location',location)
    print(pairs[para_pos[location]])
    print('best para are',bestalpha,bestn)
    
    
    w_finalo = findw(bestalpha, bestn, X_all, y_all)
    final_resulto = predict(X_test,w_finalo)#using testset to verify and produce prediction results
    finalaccuo = accuracy(final_resulto,y_test)#calculate the accuracy according to label y_test and prediction results
    finalcoo = conmat(final_resulto,y_test)
    print('The final accuracy is', finalaccuo)
    print('The confusion matrix of prediction is\n', finalcoo)
    end = datetime.datetime.now()
    print ('used time is',end-start)
    return w_finalo    

In [28]:
fit()

[[1e-07, 500], [1e-07, 1000], [1e-07, 1500], [1e-07, 2500], [1e-07, 3000], [2e-07, 500], [2e-07, 1000], [2e-07, 1500], [2e-07, 2500], [2e-07, 3000], [3e-07, 500], [3e-07, 1000], [3e-07, 1500], [3e-07, 2500], [3e-07, 3000], [4e-07, 500], [4e-07, 1000], [4e-07, 1500], [4e-07, 2500], [4e-07, 3000], [5e-07, 500], [5e-07, 1000], [5e-07, 1500], [5e-07, 2500], [5e-07, 3000], [6e-07, 500], [6e-07, 1000], [6e-07, 1500], [6e-07, 2500], [6e-07, 3000], [7e-07, 500], [7e-07, 1000], [7e-07, 1500], [7e-07, 2500], [7e-07, 3000], [8e-07, 500], [8e-07, 1000], [8e-07, 1500], [8e-07, 2500], [8e-07, 3000], [9e-07, 500], [9e-07, 1000], [9e-07, 1500], [9e-07, 2500], [9e-07, 3000], [1e-06, 500], [1e-06, 1000], [1e-06, 1500], [1e-06, 2500], [1e-06, 3000], [2e-06, 500], [2e-06, 1000], [2e-06, 1500], [2e-06, 2500], [2e-06, 3000], [3e-06, 500], [3e-06, 1000], [3e-06, 1500], [3e-06, 2500], [3e-06, 3000], [4e-06, 500], [4e-06, 1000], [4e-06, 1500], [4e-06, 2500], [4e-06, 3000], [4.9999999999999996e-06, 500], [4.999

array([-0.3602736 , -0.02769576,  0.14126452,  0.22453076])

In [23]:
from sklearn.linear_model import LogisticRegression
X = X_all
y = y_all
clf = LogisticRegression().fit(X, y)
r = clf.predict(X_test)
#accuracy(r,y_test)
#label=testset[:,data2.shape[1]-1]
#print(label)
print(clf.score(X_test, y_test))

0.7178683385579937


/home/mz/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [14]:
#yicikeyong
w_finalo = findw(9e-06, 2500, X_all, y_all)
final_resulto = predict(X_test,w_finalo)#using testset to verify and produce prediction results
finalaccuo = accuracy(final_resulto,y_test)#calculate the accuracy according to label y_test and prediction results
finalcoo = conmat(final_resulto,y_test)
print('The final accuracy is', finalaccuo)
print('The confusion matrix of prediction is\n', finalcoo)

(319,)
(319,)
The final accuracy is 0.7084639498432602
The confusion matrix of prediction is
 [[114  29]
 [ 64 112]]


In [11]:




w_finalo = findw(0.08, 2500, X_all, y_all)
final_resulto = predict(X_test,w_finalo)#using testset to verify and produce prediction results
finalaccuo = accuracy(final_resulto,y_test)#calculate the accuracy according to label y_test and prediction results
finalcoo = conmat(final_resulto,y_test)
print('The final accuracy is', finalaccuo)
print('The confusion matrix of prediction is\n', finalcoo)
end = datetime.datetime.now()

return w_finalo 

(319,)
(319,)
The final accuracy is 0.6865203761755486
The confusion matrix of prediction is
 [[107  29]
 [ 71 112]]


NameError: name 'start' is not defined

In [1]:
print(asd)

NameError: name 'asd' is not defined