In [26]:
import csv                       #use library csv to open and read csv data
import numpy as np 
import math
import datetime
import random
path='/home/mz/Desktop/winequality-red.csv'

with open(path,'r') as winedata:
    reader = csv.reader(winedata, delimiter=';') #maybe csv from mac? Set the delimiter to ';'
    rows= [row for row in reader]
    
#print (rows[0])
data=np.array(rows)               #change rows' datatype into array
dataset=np.delete(data,0,axis = 0) #delete the name row

#wdataset will be used for K-fold validation
wdataset = dataset.astype(np.float)
for n in range(0,wdataset.shape[0]): 
    #classify the quality. Positiv:1  Negativ:2
    if wdataset[n,11]>5: wdataset[n,11]=1
    else: wdataset [n,11]=0
print(wdataset)

datash = wdataset
np.random.shuffle(datash)
data0=datash




k=5
n0 = data0.shape[0]
X_test = data0[0:int(n0/k), 0:-1 ]
y_test = data0[0:int(n0/k), -1 ]
data2 = np.delete(data0, range(0,int(n0/k)),axis = 0)#delete testset from data
n1 = data2.shape[0]#number of rows in data2 for training and validation
X_all = data2[:,0:-1]
y_all = data2[:,-1]
X_valid = [[]for i in range(k)]
X_train = [[]for i in range(k)]
y_valid = [[]for i in range(k)]
y_train = [[]for i in range(k)]
trainset = [[]for i in range(k)]
for i in range(0,k):
    X_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), 0:-1])
    y_valid[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), -1])
    a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
    trainset[i] = np.delete(data2, a , axis=0)
    X_train[i] = trainset[i][:,0:-1]
    y_train[i] = trainset[i][:,-1]
    print('valid i=', i, X_train[i].shape)
    print('valid i=', i, y_train[i].shape)

[[ 7.4    0.7    0.    ...  0.56   9.4    0.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    0.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    0.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     1.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    0.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     1.   ]]
valid i= 0 (1024, 11)
valid i= 0 (1024,)
valid i= 1 (1024, 11)
valid i= 1 (1024,)
valid i= 2 (1024, 11)
valid i= 2 (1024,)
valid i= 3 (1024, 11)
valid i= 3 (1024,)
valid i= 4 (1024, 11)
valid i= 4 (1024,)


In [27]:
def sigmoid(gamma):
    if gamma < 0:
        return 1 - 1/(1 + math.exp(gamma))
    else:
        return 1/(1 + math.exp(-gamma))
    

'''
def add(data,w):
            m = data.shape[1]
            summe = np.zeros(m-1)
            for i in range(0,data.shape[0]):
                a = data[i,0:(data.shape[1]-1)]*((data[i,(data.shape[1]-1)])-sigma(w, data[i,0:(data.shape[1]-1)]))
                summe = summe + a         
            return summe    
    
def gd(w,lr,data):
            neww = w + lr*add(data,w)
            return neww
'''

def findw(lr,n,data,y_train, lam):
    traindata = data
    m = traindata.shape[1]#column number of data
    #w = [0,0,0,0,0,0,0,0,0,0,0]
    #w = [1,1,1,1,1,1,1,1,1,1,1]
    w = np.ones(m)
    #right = [0,0,0,0,0,0,0,0,0,0,0]
    #vector
    right = np.zeros(m)
    for i in range(1,n):#n times iteration
        #wt = np.array([w]).T#transport from row to column
        for j in range(0,traindata.shape[0]):
            right = right + traindata[j,]*(y_train[j]-sigmoid(np.dot(w,traindata[j,])))
            #print('right',j,right)
        #print('iteration = ',i,right)
        for l in range(0,right.shape[0]):
            right[l]=right[l]*lr
        #print(right)
        w = w + right + lam*np.sign(w)#with L1 lasso
        #print(w)
    return w



def predict(data,w):#already got w for prediction
        n = data.shape[0]
        result = np.zeros(n)
        for i in range(0,n):
            prob = sigmoid(np.dot(w,data[i,]))
            #prob = (1/math.sqrt(2*pi*sigma(w,data[i,0:n-1]))) * math.exp(-(1-np.transpose(w)*data[i,0:n-1]/2(sigma(w,data[i,0:n-1])*sigma(w,data[i,0:n-1]))))
            if prob>=0.5: result[i]=1
        return result
             
def accuracy(pred, y):#pred is result from fct predict
    real = y
    
    if pred.shape != real.shape:
        print('Error!!!')
        
    acc=0
    for i in range(pred.shape[0]):
        if pred[i]==real[i]:
            acc=acc+1
    Accuracy=acc/pred.shape[0]   
    #print('Accuracy is ',Accuracy)
    return Accuracy

def conmat(result,y):
    rv = y
    #print(result.shape)
    #print(rv.shape)
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(result.shape[0]):
        if ((result[i]==1)&(rv[i]==1)): TP = TP+1
        if ((result[i]==0)&(rv[i]==0)): TN = TN+1
        if ((result[i]==0)&(rv[i]==1)): FN = FN+1
        if ((result[i]==1)&(rv[i]==0)): FP = FP+1
    metrix = np.array([[TP,FP], [FN,TN]])
    return metrix
'''                    
def Accu(data):#the data is after prediction
        n = shape.data[0]
        m = shape.data[1]
        a = 0
        for i in range(0,n):
                if data[i,m-2]==data[i,m-1]: a=a+1
        Accuracy = a/n
        return Accuracy
  
    0
    
def kfold(k, data):
    n0 = data.shape[0]
    testset = data[0:int(n0/k), ]
    data2 = np.delete(data, range(0,int(n0/k)),axis = 0)#delete testset from data
    n1 = data2.shape[0]#number of rows in data2 for training and verti

    vertiset = [[]for i in range(k)]
    trainset = [[]for i in range(k)]
    
    for i in range(0,k):
        vertiset[i] = np.array(data2[int((i*n1)/k):int((i+1)*n1/k), :])
        print('verti i=', i, vertiset[i].shape)
        a=np.arange(int((i*n1)/k),int((i+1)*n1/k))
        trainset[i] = np.delete(data2, a , axis=0)
'''      
    
def fit():#tuning,training and testing process together
    start = datetime.datetime.now()
    a_n = 7
    iter_n= 5
    numwewant = 40
    
    alpha = np.zeros(9*a_n)
    for i in range(9):
        alpha[i]= 1e-7*(i+1)
        alpha[i+9]= 1e-6*(i+1)
        alpha[i+18]= 1e-5*(i+1)
        alpha[i+27]= 1e-4*(i+1)
        alpha[i+36]= 1e-3*(i+1)
        alpha[i+45]= 1e-2*(i+1)
        alpha[i+54]= 1e-1*(i+1)
        #alpha[i+63]= (i+1)
        #alpha[i+72]= (i+1)*10
        #alpha[i+81]= (i+1)*100
    
    #n_iteration = [500, 1000, 1500]
    n_iteration = [500, 1000, 1500, 2500, 3000]
    
    pairs = [[]for i in range(a_n*iter_n*9)]
    n = 0
    
    #offer all possibilities for pairs of alpha and iteration
    for i in range(9*a_n):
        j = 0
        while j<5:
            pairs[n] = [alpha[i], n_iteration[j]]
            n = n+1
            j = j+1
             
    print(pairs)  
    
    print('\n')
    #print(pairs)
    
    #here we chose numwewant from 9*a_n*5
    para_pos = np.array(random.sample(range(0,a_n*iter_n*9), numwewant))#generate used pairs's position
    #result = np.zeros([80,256])
    result = [[]for i in range(numwewant)]#save the predict results
    print(para_pos)
    A = np.zeros(numwewant)#the avg accuracy vector for 80 pairs
    Accu = np.zeros([numwewant,5])#Accuracy for each validation
    #ln=0
    
    for i in range(numwewant):
        print('\n')
        pos = para_pos[i]
        print('pos',pos)
        para = pairs[pos]
        print('para',para)
        for j in range(5):
            #a = para[0]
            #b = para[1]
            #print(a)
            #print(b)
            lr = para[0]
            n = para[1]
            w_model = findw(lr,n,X_train[j],y_train[j],0)#find w according to X_train and y_train
            print('fold',j,'of model',i,'finished',w_model)
            result[i] = predict(X_valid[j],w_model)#using X_valid as input to produce prediction output
            #result = predict(X_valid[j],w_model)
            #result[ln] = predict(X_valid[j],w_model)
            #ln = ln+1
            Accu[i,j]= accuracy(result[i], y_valid[j])#compare result(output prediction) and real values y_valid
            print('Accuracy is',Accu[i,j])
            if j ==4: A[i] = np.sum(Accu[i,:])/5
            if j ==4: print('\033[1;35m Average accuracy is \033[0m',A[i])          
            print('\n')
            
            
  


        
    a = np.max(A)
    pos_max = np.where(A==a)
    location = pos_max[0][0]#location is a number which used to locate which random number in random vector
    print('used position',location)
    bestalpha = pairs[para_pos[location]][0]
    bestn = pairs[para_pos[location]][1]
    print('avg A is',A)
    print('max',np.max(A))
    print('max_pos',pos_max)
    print('location',location)
    print(pairs[para_pos[location]])
    print('best para are',bestalpha,bestn)
    
    w_final = findw(bestalpha, bestn, X_all, y_all)
    final_result = predict(X_test,w_final)#using testset to verify and produce prediction results
    finalaccu = accuracy(final_result,y_test)#calculate the accuracy according to label y_test and prediction results
    finalco = conmat(final_result,y_test)
    print('The final accuracy is', finalaccu)
    print('The confusion matrix of prediction is\n', finalco)
    end = datetime.datetime.now()
    print ('used time is',end-start)
    return w_final    

In [12]:
from sklearn.linear_model import LogisticRegression
X = X_all
y = y_all
clf = LogisticRegression(C=1500).fit(X, y)
r = clf.predict(X_test)
accuracy(r,y_test)
#clf.score(r, y_test)

/home/mz/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7617554858934169

In [29]:
for i in range(100):#0-0.99 test
    w_final = findw(0.001, 500, X_all, y_all,i*0.01)
    finalresult = predict(X_test,w_final)
    finalaccu = np.zeros(1000)
    finalaccu[i] = accuracy(finalresult,y_test)
    print(finalaccu[i])
    finalco = conmat(finalresult,y_test)
    print(finalco)

0.5956112852664577
[[164 120]
 [  9  26]]
0.5956112852664577
[[165 121]
 [  8  25]]
0.5862068965517241
[[165 124]
 [  8  22]]
0.5893416927899686
[[165 123]
 [  8  23]]
0.567398119122257
[[166 131]
 [  7  15]]
0.5705329153605015
[[167 131]
 [  6  15]]
0.5705329153605015
[[166 130]
 [  7  16]]
0.5768025078369906
[[169 131]
 [  4  15]]
0.567398119122257
[[166 131]
 [  7  15]]
0.5642633228840125
[[165 131]
 [  8  15]]
0.5768025078369906
[[165 127]
 [  8  19]]
0.5768025078369906
[[165 127]
 [  8  19]]
0.5799373040752351
[[165 126]
 [  8  20]]
0.5799373040752351
[[165 126]
 [  8  20]]
0.5768025078369906
[[164 126]
 [  9  20]]
0.5799373040752351
[[164 125]
 [  9  21]]
0.5830721003134797
[[164 124]
 [  9  22]]
0.5830721003134797
[[164 124]
 [  9  22]]
0.5862068965517241
[[164 123]
 [  9  23]]
0.5893416927899686
[[165 123]
 [  8  23]]
0.5956112852664577
[[165 121]
 [  8  25]]
0.5956112852664577
[[165 121]
 [  8  25]]
0.5956112852664577
[[165 121]
 [  8  25]]
0.5956112852664577
[[165 121]
 [  8 

In [34]:
for i in range(100):#0-0.99
    w_final = findw(0.001, 500, X_all, y_all,i*0.01)
    finalresult = predict(X_test,w_final)
    finalaccu = np.zeros(1000)
    finalaccu[i] = accuracy(finalresult,y_test)
    print(finalaccu[i])

0.5956112852664577
0.5956112852664577
0.5862068965517241
0.5893416927899686
0.567398119122257
0.5705329153605015
0.5705329153605015
0.5768025078369906
0.567398119122257
0.5642633228840125
0.5768025078369906
0.5768025078369906
0.5799373040752351
0.5799373040752351
0.5768025078369906
0.5799373040752351
0.5830721003134797
0.5830721003134797
0.5862068965517241
0.5893416927899686
0.5956112852664577
0.5956112852664577
0.5956112852664577
0.5956112852664577
0.5987460815047022
0.5987460815047022
0.5987460815047022
0.5956112852664577
0.5924764890282131
0.5956112852664577
0.5956112852664577
0.6050156739811913
0.6050156739811913
0.6081504702194357
0.6081504702194357
0.6018808777429467
0.6018808777429467
0.5987460815047022
0.6018808777429467
0.6018808777429467
0.6018808777429467
0.5987460815047022
0.6018808777429467
0.6018808777429467
0.5956112852664577
0.5893416927899686
0.5893416927899686
0.6018808777429467
0.5956112852664577
0.6018808777429467
0.5956112852664577
0.5924764890282131
0.589341692789

In [35]:
for i in range(50):#0-49
    w_final = findw(0.001, 500, X_all, y_all,i)
    finalresult1 = predict(X_test,w_final)
    finalaccu1 = np.zeros(1000)
    finalaccu1[i] = accuracy(finalresult1,y_test)
    print(finalaccu1[i])

0.5956112852664577
0.5391849529780565
0.6144200626959248
0.6112852664576802
0.6175548589341693
0.6175548589341693
0.6175548589341693
0.6175548589341693
0.6175548589341693
0.6238244514106583
0.6238244514106583
0.6269592476489029
0.6269592476489029
0.6269592476489029
0.6269592476489029
0.6269592476489029
0.6269592476489029
0.6269592476489029
0.6300940438871473
0.6269592476489029
0.6238244514106583
0.6238244514106583
0.6206896551724138
0.6206896551724138
0.6206896551724138
0.6206896551724138
0.6238244514106583
0.6238244514106583
0.6238244514106583
0.6238244514106583
0.6238244514106583
0.6206896551724138
0.6206896551724138
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301


In [36]:
for i in range(100):#50-149
    w_final = findw(0.001, 500, X_all, y_all,i+50)
    finalresult1 = predict(X_test,w_final)
    finalaccu1 = np.zeros(1000)
    finalaccu1[i] = accuracy(finalresult1,y_test)
    print(finalaccu1[i])

0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.542319749216301
0.54231974

In [ ]:
from sklearn.linear_model import LogisticRegression
X = X_all
y = y_all
clf = LogisticRegression(C=1500).fit(X, y)
r = clf.predict(X_test)
accuracy(r,y_test)
#clf.score(r, y_test)