In [1]:
import numpy as np
import pandas as pd
import csv
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
import time
from sklearn import metrics
path='dataset//reddit_train.csv'
path_test='dataset//reddit_test.csv'
labels=['Overwatch','Music','conspiracy','AskReddit','worldnews','anime','hockey','baseball','funny','nba',
    'canada','soccer','nfl','trees','gameofthrones','wow','leagueoflegends','GlobalOffensive','europe','movies']


In [2]:
data = pd.read_csv(path)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(data['comments'], data['subreddits'], train_size=0.8, test_size=0.2)
print(len(X_train))

56000


In [4]:
vectorizer = CountVectorizer(stop_words='english')
print(vectorizer)
vectors_train = vectorizer.fit_transform(X_train)

# and we do the same for test data. remember to use the same vectorizer, only transform (why?)
vectors_test = vectorizer.transform(X_test)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf_idf_vectorizer = TfidfVectorizer()
vectors_train_idf = tf_idf_vectorizer.fit_transform(X_train)
vectors_test_idf = tf_idf_vectorizer.transform(X_test)

In [6]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
MNB_clf = MultinomialNB(alpha=.01)
MNB_clf.fit(vectors_train_idf, y_train)
#scores = cross_val_score(MNB_clf, vectors_train, y_train, cv=5)
#print(scores)
y_pred=MNB_clf.predict(vectors_test_idf)
print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

test accuracy: 55.21%


In [7]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(10):
    print("alpha: ", 0.0001*(i+1))
    MNB_clf = MultinomialNB(alpha=.0001*(i+1))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  0.0001
[0.51547863 0.51544091 0.50906331 0.5142015  0.51411723]
test accuracy: 52.65%
alpha:  0.0002
[0.51815505 0.51936808 0.51272435 0.51661308 0.51733381]
test accuracy: 52.90%
alpha:  0.00030000000000000003
[0.51958248 0.52097465 0.51459952 0.51866738 0.51938885]
test accuracy: 53.11%
alpha:  0.0004
[0.52020698 0.52240271 0.51593892 0.52009646 0.52090779]
test accuracy: 53.19%
alpha:  0.0005
[0.52118833 0.52383077 0.51692115 0.52036442 0.52251608]
test accuracy: 53.27%
alpha:  0.0006000000000000001
[0.52208047 0.52499107 0.51745692 0.52107896 0.52349893]
test accuracy: 53.37%
alpha:  0.0007
[0.5228834  0.52641914 0.51826056 0.52206145 0.52421372]
test accuracy: 53.46%
alpha:  0.0008
[0.52377554 0.52793645 0.51888561 0.52295463 0.52492852]
test accuracy: 53.56%
alpha:  0.0009000000000000001
[0.52422161 0.52838272 0.51924279 0.5233119  0.52564332]
test accuracy: 53.64%
alpha:  0.001
[0.52440004 0.52873974 0.52004643 0.52357985 0.52644746]
test accuracy: 53.69%


In [8]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(10):
    print("alpha: ", 0.001*(i+1))
    MNB_clf = MultinomialNB(alpha=.001*(i+1))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  0.001
[0.52440004 0.52873974 0.52004643 0.52357985 0.52644746]
test accuracy: 53.69%
alpha:  0.002
[0.52823624 0.53463049 0.52451112 0.52920686 0.53046819]
test accuracy: 54.08%
alpha:  0.003
[0.53162637 0.53748661 0.52745781 0.53152912 0.53386347]
test accuracy: 54.28%
alpha:  0.004
[0.53394594 0.5394502  0.52870792 0.53313683 0.53672266]
test accuracy: 54.55%
alpha:  0.005
[0.53599786 0.54096751 0.53049379 0.5350125  0.5384203 ]
test accuracy: 54.69%
alpha:  0.006
[0.53778214 0.54221707 0.53236896 0.53644159 0.54110079]
test accuracy: 54.78%
alpha:  0.007
[0.53840664 0.54302035 0.53352978 0.5375134  0.54261973]
test accuracy: 54.89%
alpha:  0.008
[0.53965563 0.54462692 0.53442272 0.53778135 0.54395997]
test accuracy: 55.00%
alpha:  0.009000000000000001
[0.54054777 0.54551946 0.53513707 0.53849589 0.54547891]
test accuracy: 55.15%
alpha:  0.01
[0.54161834 0.546412   0.53629788 0.53974634 0.54610436]
test accuracy: 55.21%


In [9]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(10):
    print("alpha: ", 0.01*(i+1))
    MNB_clf = MultinomialNB(alpha=.01*(i+1))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  0.01
[0.54161834 0.546412   0.53629788 0.53974634 0.54610436]
test accuracy: 55.21%
alpha:  0.02
[0.5458114  0.55274902 0.54236985 0.54653448 0.55173338]
test accuracy: 55.82%
alpha:  0.03
[0.54973682 0.55614066 0.54710242 0.55234012 0.55673695]
test accuracy: 56.29%
alpha:  0.04
[0.55259167 0.5581935  0.54960264 0.55537692 0.55888134]
test accuracy: 56.49%
alpha:  0.05
[0.5547328  0.56015709 0.55335298 0.55814577 0.56147248]
test accuracy: 56.60%
alpha:  0.06
[0.55589259 0.56087112 0.55576391 0.55993212 0.56129378]
test accuracy: 56.61%
alpha:  0.07
[0.55633866 0.56203142 0.55647826 0.56037871 0.56236598]
test accuracy: 56.69%
alpha:  0.08
[0.55642787 0.56337022 0.55647826 0.56064666 0.56308077]
test accuracy: 56.71%
alpha:  0.09
[0.55687394 0.56435202 0.55754978 0.56171847 0.56281272]
test accuracy: 56.83%
alpha:  0.1
[0.55839058 0.56435202 0.55808554 0.56180779 0.56379557]
test accuracy: 56.94%


In [10]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(10):
    print("alpha: ", 0.1*(i+1))
    MNB_clf = MultinomialNB(alpha=.1*(i+1))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  0.1
[0.55839058 0.56435202 0.55808554 0.56180779 0.56379557]
test accuracy: 56.94%
alpha:  0.2
[0.55955036 0.56569082 0.55996071 0.56162915 0.56191923]
test accuracy: 57.30%
alpha:  0.30000000000000004
[0.55705237 0.56426276 0.55826413 0.55939621 0.56165118]
test accuracy: 57.03%
alpha:  0.4
[0.55526809 0.56274545 0.55665684 0.55707395 0.55977484]
test accuracy: 56.79%
alpha:  0.5
[0.55428673 0.55917529 0.55460309 0.5532333  0.55798785]
test accuracy: 56.56%
alpha:  0.6000000000000001
[0.55178874 0.55730096 0.5515671  0.5522508  0.55691565]
test accuracy: 56.26%
alpha:  0.7000000000000001
[0.54929075 0.5558729  0.54915617 0.55055377 0.55343102]
test accuracy: 56.04%
alpha:  0.8
[0.54679276 0.55301678 0.54728101 0.54778492 0.55030379]
test accuracy: 55.84%
alpha:  0.9
[0.54527612 0.5512317  0.54531655 0.54537335 0.5481594 ]
test accuracy: 55.68%
alpha:  1.0
[0.54358105 0.54953588 0.54353067 0.54385495 0.54619371]
test accuracy: 55.40%


In [11]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(10):
    print("alpha: ", 1*(i+1))
    MNB_clf = MultinomialNB(alpha=1*(i+1))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  1
[0.54358105 0.54953588 0.54353067 0.54385495 0.54619371]
test accuracy: 55.40%
alpha:  2
[0.52698724 0.53007854 0.52406465 0.52777778 0.53145104]
test accuracy: 53.78%
alpha:  3
[0.51512178 0.51802928 0.51299223 0.51607717 0.5194782 ]
test accuracy: 52.48%
alpha:  4
[0.50646802 0.50678329 0.50325922 0.50598428 0.5086669 ]
test accuracy: 51.58%
alpha:  5
[0.49817111 0.5011603  0.49665149 0.49866024 0.50062545]
test accuracy: 50.89%
alpha:  6
[0.49040949 0.49518029 0.48977587 0.49267596 0.49410293]
test accuracy: 50.19%
alpha:  7
[0.48425372 0.48884327 0.48290026 0.48642372 0.48820586]
test accuracy: 49.61%
alpha:  8
[0.47934695 0.48339879 0.4780784  0.48088603 0.48195139]
test accuracy: 49.13%
alpha:  9
[0.47444018 0.47831132 0.47432807 0.47597356 0.47569693]
test accuracy: 48.52%
alpha:  10
[0.46899813 0.47313459 0.47084561 0.47115041 0.4713188 ]
test accuracy: 48.17%


In [12]:
###MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
for i in range(30):
    print("alpha: ", 0.1+0.01*(i))
    MNB_clf = MultinomialNB(alpha=0.1+.01*(i))
    MNB_clf.fit(vectors_train_idf, y_train)
    scores = cross_val_score(MNB_clf, vectors_train_idf, y_train, cv=5)
    print(scores)
    y_pred=MNB_clf.predict(vectors_test_idf)
    print("test accuracy: %0.2f%%" %((y_pred==y_test).astype(np.int).mean()*100))

alpha:  0.1
[0.55839058 0.56435202 0.55808554 0.56180779 0.56379557]
test accuracy: 56.94%
alpha:  0.11
[0.55812294 0.56461978 0.55817484 0.56011075 0.56361687]
test accuracy: 57.03%
alpha:  0.12000000000000001
[0.55785529 0.56461978 0.55772837 0.56118257 0.56317012]
test accuracy: 57.04%
alpha:  0.13
[0.55821215 0.5651553  0.55817484 0.56189711 0.56361687]
test accuracy: 57.06%
alpha:  0.14
[0.55901508 0.56417351 0.5587106  0.56207574 0.56334882]
test accuracy: 57.04%
alpha:  0.15000000000000002
[0.55919351 0.56408426 0.55844272 0.56305824 0.56317012]
test accuracy: 57.06%
alpha:  0.16
[0.55919351 0.56417351 0.55862131 0.56198642 0.56263402]
test accuracy: 57.12%
alpha:  0.17
[0.55937193 0.56444127 0.55879989 0.56189711 0.56325947]
test accuracy: 57.23%
alpha:  0.18
[0.55919351 0.56461978 0.55942495 0.56153984 0.56334882]
test accuracy: 57.28%
alpha:  0.19
[0.55963958 0.56524456 0.55951424 0.56189711 0.56236598]
test accuracy: 57.31%
alpha:  0.2
[0.55955036 0.56569082 0.55996071 0.561

In [13]:
from sklearn.linear_model import LogisticRegression
tf_idf_vectorizer1=TfidfVectorizer(sublinear_tf='False')
vectors_train_idf_1 = tf_idf_vectorizer1.fit_transform(X_train)
vectors_test_idf_1 = tf_idf_vectorizer1.transform(X_test)
for i in range(20):
    c=0.2*i+0.1
    clf = LogisticRegression(C=c)
    print('C=',c)
    scores = cross_val_score(clf, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
from sklearn.linear_model import SGDClassifier
tf_idf_vectorizer1=TfidfVectorizer(sublinear_tf='False')
vectors_train_idf_1 = tf_idf_vectorizer1.fit_transform(X_train)
vectors_test_idf_1 = tf_idf_vectorizer1.transform(X_test)
for i in range(10):
    a=0.1*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

0.1
Accuracy: 0.19758 (+/- 0.02822)
0.2
Accuracy: 0.05516 (+/- 0.00378)
0.30000000000000004
Accuracy: 0.05157 (+/- 0.00164)
0.4
Accuracy: 0.05252 (+/- 0.00354)
0.5
Accuracy: 0.06100 (+/- 0.01062)
0.6000000000000001
Accuracy: 0.05243 (+/- 0.00378)
0.7000000000000001
Accuracy: 0.05007 (+/- 0.00023)
0.8
Accuracy: 0.05344 (+/- 0.00504)
0.9
Accuracy: 0.05196 (+/- 0.00272)
1.0
Accuracy: 0.05118 (+/- 0.00122)


In [17]:
from sklearn.linear_model import SGDClassifier
for i in range(10):
    a=0.01*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

0.01
Accuracy: 0.54147 (+/- 0.00238)
0.02
Accuracy: 0.53955 (+/- 0.00343)
0.03
Accuracy: 0.53395 (+/- 0.00234)
0.04
Accuracy: 0.50420 (+/- 0.00246)
0.05
Accuracy: 0.45090 (+/- 0.01258)
0.06
Accuracy: 0.36738 (+/- 0.01842)
0.07
Accuracy: 0.33773 (+/- 0.03331)
0.08
Accuracy: 0.29851 (+/- 0.01611)
0.09
Accuracy: 0.25182 (+/- 0.00712)
0.1
Accuracy: 0.18725 (+/- 0.02977)


In [18]:
from sklearn.linear_model import SGDClassifier
for i in range(10):
    a=0.001*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

0.001
Accuracy: 0.54157 (+/- 0.00301)
0.002
Accuracy: 0.54163 (+/- 0.00261)
0.003
Accuracy: 0.54107 (+/- 0.00262)
0.004
Accuracy: 0.54102 (+/- 0.00280)
0.005
Accuracy: 0.54111 (+/- 0.00272)
0.006
Accuracy: 0.54139 (+/- 0.00190)
0.007
Accuracy: 0.54100 (+/- 0.00295)
0.008
Accuracy: 0.54154 (+/- 0.00290)
0.009000000000000001
Accuracy: 0.54182 (+/- 0.00206)
0.01
Accuracy: 0.54075 (+/- 0.00209)


In [19]:
from sklearn.linear_model import SGDClassifier
for i in range(10):
    a=0.0001*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

0.0001
Accuracy: 0.55291 (+/- 0.00173)
0.0002
Accuracy: 0.54863 (+/- 0.00187)
0.00030000000000000003
Accuracy: 0.54689 (+/- 0.00251)
0.0004
Accuracy: 0.54609 (+/- 0.00308)
0.0005
Accuracy: 0.54575 (+/- 0.00251)
0.0006000000000000001
Accuracy: 0.54400 (+/- 0.00231)
0.0007
Accuracy: 0.54313 (+/- 0.00356)
0.0008
Accuracy: 0.54321 (+/- 0.00353)
0.0009000000000000001
Accuracy: 0.54236 (+/- 0.00251)
0.001
Accuracy: 0.54184 (+/- 0.00265)


In [20]:
from sklearn.linear_model import SGDClassifier
for i in range(10):
    a=0.00001*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

1e-05
Accuracy: 0.55263 (+/- 0.00448)
2e-05
Accuracy: 0.55807 (+/- 0.00293)
3.0000000000000004e-05
Accuracy: 0.55773 (+/- 0.00155)
4e-05
Accuracy: 0.55723 (+/- 0.00177)
5e-05
Accuracy: 0.55612 (+/- 0.00212)
6.000000000000001e-05
Accuracy: 0.55550 (+/- 0.00240)
7.000000000000001e-05
Accuracy: 0.55493 (+/- 0.00168)
8e-05
Accuracy: 0.55364 (+/- 0.00242)
9e-05
Accuracy: 0.55355 (+/- 0.00250)
0.0001
Accuracy: 0.55345 (+/- 0.00219)


In [21]:
from sklearn.linear_model import SGDClassifier
for i in range(10):
    a=0.000001*(i+1)
    print(a)
    lsvm = SGDClassifier(average=True, alpha=a, max_iter=20, tol=None)
    scores = cross_val_score(lsvm, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))

1e-06
Accuracy: 0.51446 (+/- 0.00275)
2e-06
Accuracy: 0.52445 (+/- 0.00441)
3e-06
Accuracy: 0.52957 (+/- 0.00350)
4e-06
Accuracy: 0.53495 (+/- 0.00319)
4.9999999999999996e-06
Accuracy: 0.53932 (+/- 0.00296)
6e-06
Accuracy: 0.54297 (+/- 0.00457)
7e-06
Accuracy: 0.54620 (+/- 0.00520)
8e-06
Accuracy: 0.54872 (+/- 0.00402)
9e-06
Accuracy: 0.55084 (+/- 0.00378)
9.999999999999999e-06
Accuracy: 0.55263 (+/- 0.00373)


In [ ]:
from sklearn.svm import LinearSVC
for i in range(10):
    a=0.1*(i+1)
    print(a)
    clf = LinearSVC(C=a)
    scores = cross_val_score(clf, vectors_train_idf_1, y_train, cv=5, scoring='accuracy')
    print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std()))